#!/bin/bash

brew install jq
sudo apt-get install jq
# optional argument handling
if [[ "$1" == "login" ]]
then
    pks login -a $2 -u $3 --skip-ssl-validation
    exit 0
fi

# optional argument handling
if [[ "$1" == "clusters" ]]
then
    pks clusters
    exit 0
fi

if [[ "$1" == "uuac" && "$2" = "adduser" ]]
then
	uaac target $3
	uaac token owner get opsman -s ""
	auth_secret=$( curl -k  “https://opsman.flhrnet.local/api/v0/deployed/director/credentials/uaa_admin_user_credentials” -X GET -H “Authorization: Bearer <Authorization Token>”  | jq '.secret' ) 
	uaac token client get admin -s $auth_secret
	uaac user add pksadmin --emails $4 -p $5
	uaac member add pks.clusters.admin pksadmin
	exit 0
fi
	echo "I am a plugin named kubectl-foo"


